# Generated by Django 3.1.1 on 2020-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20201008_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='images')),
                ('name', models.CharField(max_length=20)),
                ('postion', models.CharField(max_length=20)),
            ],
        ),
    ]
