# Generated by Django 3.1.1 on 2020-10-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_testimonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonial',
            new_name='guest',
        ),
    ]
