# Generated by Django 3.1.1 on 2020-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20201011_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
