# Generated by Django 3.1.1 on 2020-10-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_author_singleblog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='singleblog',
            new_name='blogsingle',
        ),
    ]
