# Generated by Django 3.1.1 on 2020-10-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20201012_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogsingle',
            new_name='singleblog',
        ),
    ]
