# Generated by Django 3.1.1 on 2020-10-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20201012_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleblog',
            name='description',
            field=models.TextField(),
        ),
    ]
