# Generated by Django 3.1.1 on 2020-10-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20201012_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleblog',
            name='categories',
            field=models.ManyToManyField(to='blogs.Category'),
        ),
    ]
