# Generated by Django 3.1.1 on 2020-10-12 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0020_singleblog_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='categories',
        ),
        migrations.AddField(
            model_name='index',
            name='categoriess',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.category'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='singleblog',
            name='categories',
        ),
        migrations.AddField(
            model_name='singleblog',
            name='categories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.category'),
        ),
    ]
