# Generated by Django 3.1.1 on 2020-10-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20201012_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timestame',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
