# Generated by Django 3.1.1 on 2020-10-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_blog_timestame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='timestame',
            new_name='timestames',
        ),
    ]
