# Generated by Django 3.1.1 on 2020-10-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20201013_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestames',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
